/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine;

/**
 *
 * @author rmendes
 */
public class Bolachas extends javax.swing.JFrame {
        Produto ahoy = new Produto(1, "Chips Ahoy", 1.35f);
        Produto oreo = new Produto(8, "Oreo", 1.65f);
        Produto tuc = new Produto(2, "Tuc", 1.45f);
        Produto maria = new Produto(3, "Maria", 2.00f);
        Produto fili = new Produto(4, "Filipinos", 1.75f);
        Produto wafe = new Produto(5, "Wafers", 1.15f);
        Produto dige = new Produto(6, "Digestivas", 1.05f);
        Produto torr = new Produto(7, "Torradas", 1.15f);
    /**
     * Creates new form Chocolates
     */
    public Bolachas() {
        initComponents();
        
        //String s = Float.toString(cola.Preco);
        //PrecoBox.setText(s + "€");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomeBox = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BuyBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Troco = new javax.swing.JTextField();
        MoneyInput = new javax.swing.JTextField();
        PrecoBox = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        kitBTN = new javax.swing.JButton();
        boundBTN = new javax.swing.JButton();
        tobBTN = new javax.swing.JButton();
        mmBTN = new javax.swing.JButton();
        milkaBTN = new javax.swing.JButton();
        maltBTN = new javax.swing.JButton();
        snickBTN = new javax.swing.JButton();
        lionBTN = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        img.setPreferredSize(new java.awt.Dimension(255, 255));

        nomeBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setText("Preço:");

        jLabel4.setText("Inserir Dinheiro");

        BuyBTN.setText("Comprar");
        BuyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyBTNActionPerformed(evt);
            }
        });

        jLabel5.setText("Troco:");

        PrecoBox.setEditable(false);
        PrecoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeBox, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Troco)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PrecoBox, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addComponent(jLabel4)
                        .addComponent(BuyBTN)
                        .addComponent(jLabel5)
                        .addComponent(MoneyInput)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PrecoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoneyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(BuyBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Troco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kitBTN.setText("Filipinos");
        kitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitBTNActionPerformed(evt);
            }
        });

        boundBTN.setText("Wafers");
        boundBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundBTNActionPerformed(evt);
            }
        });

        tobBTN.setText("Torradas");
        tobBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tobBTNActionPerformed(evt);
            }
        });

        mmBTN.setText("Chips Ahoy");
        mmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmBTNActionPerformed(evt);
            }
        });

        milkaBTN.setText("Oreo");
        milkaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkaBTNActionPerformed(evt);
            }
        });

        maltBTN.setText("Tuc");
        maltBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltBTNActionPerformed(evt);
            }
        });

        snickBTN.setText("Maria");
        snickBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snickBTNActionPerformed(evt);
            }
        });

        lionBTN.setText("Digestivas");
        lionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lionBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lionBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mmBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(milkaBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maltBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boundBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(snickBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tobBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmBTN)
                    .addComponent(milkaBTN)
                    .addComponent(maltBTN)
                    .addComponent(snickBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lionBTN)
                    .addComponent(kitBTN)
                    .addComponent(boundBTN)
                    .addComponent(tobBTN)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrecoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoBoxActionPerformed

    private void lionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lionBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dige.jpg")));
    String s = Float.toString(dige.Preco);
    nomeBox.setText(dige.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_lionBTNActionPerformed

    private void maltBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tuc.jpg")));
    String s = Float.toString(tuc.Preco);
    nomeBox.setText(tuc.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_maltBTNActionPerformed

    private void mmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahoy.jpg")));
    String s = Float.toString(ahoy.Preco);
    nomeBox.setText(ahoy.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_mmBTNActionPerformed

    private void milkaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkaBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oreo.jpg")));
    String s = Float.toString(oreo.Preco);
    nomeBox.setText(oreo.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_milkaBTNActionPerformed

    private void kitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fili.jpg")));
    String s = Float.toString(fili.Preco);
    nomeBox.setText(fili.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_kitBTNActionPerformed

    private void boundBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wafe.jpg")));
    String s = Float.toString(wafe.Preco);
    nomeBox.setText(wafe.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_boundBTNActionPerformed

    private void snickBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snickBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maria.jpg")));
    String s = Float.toString(maria.Preco);
    nomeBox.setText(maria.Nome);
    PrecoBox.setText(s + "€");
    }//GEN-LAST:event_snickBTNActionPerformed

    private void tobBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tobBTNActionPerformed
    img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/torr.jpg")));
    String s = Float.toString(torr.Preco);
    nomeBox.setText(torr.Nome);
    PrecoBox.setText(s + "€");
    
    }//GEN-LAST:event_tobBTNActionPerformed

    private void BuyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyBTNActionPerformed
        String s = PrecoBox.getText();
        String sub = s.substring(0, s.length()-1);
        float p = Float.parseFloat(sub);
        float i = Float.parseFloat(MoneyInput.getText());
        float t = (i-p);   
        String formated = String.format("%.2f", t);
        Troco.setText(formated);
    }//GEN-LAST:event_BuyBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bolachas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Bolachas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuyBTN;
    private javax.swing.JTextField MoneyInput;
    private javax.swing.JTextField PrecoBox;
    private javax.swing.JTextField Troco;
    private javax.swing.JButton boundBTN;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton kitBTN;
    private javax.swing.JButton lionBTN;
    private javax.swing.JButton maltBTN;
    private javax.swing.JButton milkaBTN;
    private javax.swing.JButton mmBTN;
    private javax.swing.JLabel nomeBox;
    private javax.swing.JButton snickBTN;
    private javax.swing.JButton tobBTN;
    // End of variables declaration//GEN-END:variables
}
